<?php
/**
 * @file
 * Provides the ReportFormatter interface.
 * 
 * @package color_reporting
 */

namespace OttawaDeveloper\Tools\ColorAnalyzer\Reports;

/**
 * Implementations of this class are used to format a report.
 * 
 * @package color_reporting
 */
interface ReportFormatter {

  /**
   * Called when the report is about to begin.
   */
  public function start();
  
  /**
   * Called with the array of header names.
   * 
   * @param array $header
   *   The header names, keyed by a value unique to the ReportComponent.
   */
  public function formatHeader(array $header);
  
  /**
   * Called with the array of row values, as generated by the ReportComponent.
   * 
   * @param array $row
   */
  public function formatRow(array $row);
  
  /**
   * Called when all the rows have been called.
   */
  public function end();
  
}
